class Configs:
    def __init__(self):
        self.device = "cuda:0"                     # device
        self.train_batch_size = 8                 # Batch size
        self.task_name = 'reconstruction'          # Example task name
        self.seq_len = 100                         # Sequence length
        self.freq_seq_len = 50                     # Frequency sequence length
        self.output_attention = False              # Whether to output attention weights
        self.d_model = 256                         # Model final dimension
        self.patch_d_model = 64                    # Patch encode dimension
        self.embed = 'timeF'                       # Time encoding method
        self.freq = 'h'                            # Time frequency
        self.joint_train = False                   # Joint training or not
        self.num_subjects = 10                     # num_subjects
        self.dropout = 0.25                        # Dropout rate
        self.factor = 1                            # Attention scaling factor
        self.n_heads = 4                           # Number of attention heads
        self.encode_layers = 6                     # Number of encoder layers
        self.d_ff = 1024                            # Dimension of the feedforward network
        self.activation = 'gelu'                   # Activation function
        self.enc_in = 63                           # Encoder input dimension (example value)
        self.padding_patch = 'end'                 # Padding Path help to be modified to general case
        self.patch_len = 10                        # Patch len
        self.patch_stride = 4                      # Patch stride
        self.num_train_epochs = 50                  # Train epochs number
        self.learning_rate = 1e-3                  # Learning rate to use
        self.weight_decay = 1e-2                   # Weight decay to use
        self.extra_submodal_dim = 32               # Submodality dim
        self.log_with = "wandb"                    # The integration to report the results and logs to
        self.gradient_accumulation_steps = 4      # Gradient accumulation steps
        # pretrained model path = "runwayml/stable-diffusion-v1-5/"